# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [parker, ghost]
patreon: # Replace with a single Patreon username mouse3687
open_collective: # Replace with a single Open Collective username hunterz.io
ko_fi: # Replace with a single Ko-fi username mouse3687
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., tor.onion
liberapay: # Replace with a single Liberapay username mouse3687
issuehunt: # Replace with a single IssueHunt username mouse3687
otechie: # Replace with a single Otechie username mouse3687
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://Marlboro.com','https://tjhlaw.com','https://vodoo.io','https://mymiracleband.org', 'https://knightlinelegal.com']
